// console.log("---------process.env", process.env);

// ENV Variables
export const FUSION_ACCOUNTS_STRING =
  process.env.FUSION_ACCT_LAMBDA_ACCESS_ROLE_ARN || "";
export const RESOURCES_STACK_PRFIX = process.env.RESOURCES_STACK_PRFIX;
export const APP_NAME = process.env.APP_NAME;
export const ACCT_NAME = process.env.ACCT_NAME;
export const REGION = process.env.REGION;
export const STAGE = process.env.STAGE!;
export const PUBLIC_COGNITO_USER_POOL = process.env.PUBLIC_COGNITO_USER_POOL;
export const PUBLIC_COGNITO_CLIENT_ID = process.env.PUBLIC_COGNITO_CLIENT_ID;
export const DB_ENDPOINT = process.env.DB_ENDPOINT!;
export const SECRET_NAME = process.env.DATABASE_SECRET_ARN!;
export const MEDIA_BUCKET_NAME = process.env.MEDIA_BUCKET_NAME;
export const OPEN_AI_API_KEY = process.env.OPEN_AI_API_KEY;
export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
export const S3_URL = process.env.S3_URL;
export const WEBSOCKET_URL = process.env.WEBSOCKET_URL;
export const FUSION_ACCT_LAMBDA_ACCESS_ROLE_SESSION_NAME =
  process.env.FUSION_ACCT_LAMBDA_ACCESS_ROLE_SESSION_NAME;
export const MAIN_ACCT_ACCESS_ROLE_ARN = process.env.MAIN_ACCT_ACCESS_ROLE_ARN;
export const MAIN_ACCT_ACCESS_ROLE_SESSION_NAME =
  process.env.MAIN_ACCT_ACCESS_ROLE_SESSION_NAME;
export const YTCOMB_ACCT_ACCESS_ROLE_ARN =
  process.env.YTCOMB_ACCT_ACCESS_ROLE_ARN;
export const YTCOMB_ACCT_ACCESS_ROLE_SESSION_NAME =
  process.env.YTCOMB_ACCT_ACCESS_ROLE_SESSION_NAME;
export const HTTP_API_URL = process.env.YTCOMB_ACCT_ACCESS_ROLE_SESSION_NAME;
// ENV Variables

//Table Names
export const ACCT_FILEIMPORTS = "acct_file_imports";
export const SYSTEM_USERS = "sys_user";
export const ACCOUNT_TYPES_TABLE_NAME = "account_types";
export const ACCOUNTS_TABLE_NAME = "accounts";
export const ACCOUNT_UPLOAD_DESIGN_TABLE_NAME = "acct_upload_designs";
export const ACCOUNT_IMPORTER_UPLOADS_TABLE_NAME = "acct_importer_uploads";
export const GLOBAL_ACCOUNT_SETTING_TABLE_NAME = "global_account_settings";
export const ACCOUNT_USER_TYPES_TABLE_NAME = "acct_user_types";
export const ACCOUNT_GUIS_TABLE_NAME = "acct_guis";
export const ACCOUNT_USER_SUBSCRIPTION = "account_user_subscriptions";
export const ACCOUNT_DATASETS_TABLE_NAME = "acct_datasets";
export const ACCOUNT_GF_APPS = "acct_gf_apps";
export const ACCOUNT_MEDIA_TABLE_NAME = "media";
export const ACCOUNT_SKILL_SESSION_TABLE_NAME = "skill_session";
export const ACCOUNT_SKILL_SESSION_DATA_TABLE_NAME = "skill_session_data";
export const ACCOUNT_JOB_SESSION_TABLE_NAME = "job_session";
export const ACCOUNT_JOB_SESSION_DATA_TABLE_NAME = "job_session_data";
export const ACCOUNT_GF_DASHBOARD_WIDGET_TABLE_NAME =
  "acct_gf_dashboard_widgets";
export const ACCOUNT_DATASET_DESIGN_TABLE_NAME = "acct_dataset_designs";
export const FUSION_SCHEDULES_TABLE_NAME = "scheduled_fusions";
export const ACCOUNT_KNOWLEDGEBASE = "acct_knowledgebase";
export const SOCKET = "socket";
export const FOLDERS = "folders";
export const ACCOUNT_PRESNTATIONS_TABLE_NAME = "acct_presentations";
export const ACCOUNT_PRESNTATION_SLIDES_TABLE_NAME = "acct_presentation_slides";
export const ACCOUNT_VECTOR_KNOWLEDGEBASE_TABLE_NAME =
  "acct_vector_knowledgebase";
export const ACCOUNT_FINE_TUNE_KNOWLEDGEBASE_TABLE_NAME =
  "acct_fine_tune_knowledgebase";
export const ACCOUNT_VECTOR_KNOWLEDGEBASE_TOPICS_TABLE_NAME =
  "acct_vector_knowledgebase_topics";
export const ACCOUNT_FINE_TUNE_KNOWLEDGEBASE_TOPICS_TABLE_NAME =
  "acct_fine_tune_knowledgebase_topics";
export const ACCOUNT_VECTOR_KNOWLEDGEBASE_MESSAGES_TABLE_NAME =
  "acct_vector_knowledgebase_messages";
export const ACCOUNT_FINE_TUNE_KNOWLEDGEBASE_MESSAGES_TABLE_NAME =
  "acct_fine_tune_knowledgebase_messages";
export const SKILL_INTENTS_TABLE_NAME = "skill_intents";
export const CREDIT_TYPES = "credit_types";
export const SEAT_TYPES = "seat_types";
export const PACKAGES = "packages";
export const PACKAGES_CREDIT_SETTING = "package_credit_settings";
export const PACKAGES_SEAT_SETTING = "package_seat_settings";
export const TRANSACTION_HISTORY = "transaction_history";
export const ACCOUNT_CREDIT = "account_credit";
export const APP_CONFIGURATION = "app-configuration";
export const USER_MENU_TEMPLATE = "user_menu_templates";
export const USER_MENU_ITEM = "user_menu_items";
export const ACCT_CSV_IMPORTS = "acct_csv_imports";
export const ACCT_FUSIONS_QUEUE = "acct_fusion_queue";
export const ACCT_GLOBAL_GFML_FUNCTIONS = "acct_global_gfml_functions";
export const ACCOUNT_SOC_TASKS_TABLE_NAME = "acct_soc_tasks";
export const FOLDER_TABLE_NAME = "acct_folders";
export const SOCKET_TABLE_NAME = "socket_connections";
export const GUI_PARAMS = "gui_params";
export const FUSION_SESSIONS = "fusion_sessions";
export const envTableNames = {
  DYNAMODB_ACCT_FILEIMPORTS: `${ACCT_FILEIMPORTS}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_CSV_IMPORTS: `${ACCT_CSV_IMPORTS}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSIONS_QUEUE: `${ACCT_FUSIONS_QUEUE}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SYS_USERS_TABLE: `${SYSTEM_USERS}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_GLOBAL_ACCOUNT_SETTINGS: `${GLOBAL_ACCOUNT_SETTING_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_UPLOAD_DESIGN: `${ACCOUNT_UPLOAD_DESIGN_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_IMPORTER_UPLOADS: `${ACCOUNT_IMPORTER_UPLOADS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCOUNT_DATASET: `${ACCOUNT_DATASETS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_USER_TYPES: `${ACCOUNT_USER_TYPES_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_GUIS: `${ACCOUNT_GUIS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCOUNT_USER_SUBSCRIPTION: `${ACCOUNT_USER_SUBSCRIPTION}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_GF_APPS: `${ACCOUNT_GF_APPS}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_GLOBAL_GFML_FUNCTIONS: `${ACCT_GLOBAL_GFML_FUNCTIONS}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_APP_GFML_FUNCTIONS: `acct_3p_app_gfml_functions-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_APPS: `acct_3p_apps-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_APP_WEBHOOKS: `acct_3p_app_webhook-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_APP_RPS: `acct_3p_app_rp-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_APP_CONNECTIONS: `acct_3p_app_connections-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_CONFIGS: `acct_3p_app_configs-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_3P_ACTIONS: `acct_3p_app_actions-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSIONS: `acct_fusions-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_FLOWS: `acct_fusion_flows-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_HISTORY: `acct_fusion_histories-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_FLOW_HISTORY: `acct_fusion_flows_histories-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_WEBHOOK: `acct_fusion_webhooks-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_CONNECTION: `acct_fusion_connections-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_SESSION: `acct_fusion_sessions-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_SESSION_V2: `acct_fusion_sessions_v2-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SOCKET_CONNECTION: `${SOCKET_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SCHEDULED_FUSIONS: `${FUSION_SCHEDULES_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SCHEDULED_FUSIONS_V2: `scheduled_fusions_v2-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_USER_ACTIVITY: `acct_user_activity-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_UNIVERSAL_EVENTS: `acct_universal_events-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_UNIVERSAL_TAGS: `acct_universal_tags-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_UNIVERSAL_NOTES: `acct_universal_notes-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_GF_GUIS: `acct_gf_guis-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FUSION_SETS: `acct_fusion_sets-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FOLDERS: `${FOLDER_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SYS_ICONS: `sys_icons-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_GF_DASHBOARD_WIDGETS: `${ACCOUNT_GF_DASHBOARD_WIDGET_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_PRESENTATIONS: `${ACCOUNT_PRESNTATIONS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_VECTOR_KNOWLEDGEBASE: `${ACCOUNT_VECTOR_KNOWLEDGEBASE_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FINE_TUNE_KNOWLEDGEBASE: `${ACCOUNT_FINE_TUNE_KNOWLEDGEBASE_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_SYLAR_CHAT_SESSION: `sylar_chat_session-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_SYLAR_CHAT_MESSAGES: `sylar_chat_messages-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_SYLAR_CHAT_LOGS: `sylar_chat_log-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_VECTOR_KNOWLEDGEBASE_TOPICS: `${ACCOUNT_VECTOR_KNOWLEDGEBASE_TOPICS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FINE_TUNE_KNOWLEDGEBASE_TOPICS: `${ACCOUNT_FINE_TUNE_KNOWLEDGEBASE_TOPICS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_VECTOR_KNOWLEDGEBASE_MESSAGES: `${ACCOUNT_VECTOR_KNOWLEDGEBASE_MESSAGES_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_FINE_TUNE_KNOWLEDGEBASE_MESSAGES: `${ACCOUNT_FINE_TUNE_KNOWLEDGEBASE_MESSAGES_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SKILL_INTENTS: `${SKILL_INTENTS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SKILL_SESSION_DATA: `${ACCOUNT_SKILL_SESSION_DATA_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_JOB_SESSION_DATA: `${ACCOUNT_JOB_SESSION_DATA_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_CREDIT_TYPES: `${CREDIT_TYPES}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_SEAT_TYPES: `${SEAT_TYPES}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_PACKAGES: `${PACKAGES}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_PACKAGES_CREDIT_SETTING: `${PACKAGES_CREDIT_SETTING}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_PACKAGES_SEAT_SETTING: `${PACKAGES_SEAT_SETTING}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_APP_CONFIGURATION: `${APP_CONFIGURATION}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_DATASET_DESIGN: `${ACCOUNT_DATASET_DESIGN_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
  DYNAMODB_ACCT_SOC_TASKS: `${ACCOUNT_SOC_TASKS_TABLE_NAME}-${RESOURCES_STACK_PRFIX}-${STAGE}`,
};

export const MAINPOOLS = {
  USER_MNG: "user-mng",
  DEV_SETT: "dev-sett",
  GUI_FUSION: "gui-fusion",
  DATA_MNG: "data-mng",
  PUBLIC_1: "public-1",
  WEBSOCKET: "websocket",
} as const;
export const MAINPOOLS_APPNAME = {
  USER_MNG: `${APP_NAME}-${MAINPOOLS.USER_MNG}`,
  DEV_SETT: `${APP_NAME}-${MAINPOOLS.DEV_SETT}`,
  GUI_FUSION: `${APP_NAME}-${MAINPOOLS.GUI_FUSION}`,
  DATA_MNG: `${APP_NAME}-${MAINPOOLS.DATA_MNG}`,
  PUBLIC_1: `${APP_NAME}-${MAINPOOLS.PUBLIC_1}`,
  WEBSOCKET: `${APP_NAME}-${MAINPOOLS.WEBSOCKET}`,
} as const;

export const FUSION_ACCT_LAMBDA_ACCESS_ROLE_ARNS =
  FUSION_ACCOUNTS_STRING?.split(",");

export const ENCRYPTIONSECRET = "MAIN_ACCT_ACCESS_ROLE_SESSION_NAME";

export const MASTER_ACCOUNT_ID = "master-account";

//Folder Resources
export const RESOURCES: any = {
  "dataset-design": "acct_dataset_designs",
  dataset: "acct_datasets",
  "datacard-design": "acct_datacard_designs",
  "universal-event": "acct_universal_events",
  "account-user": "sys_users",
  "user-type": "acct_user_types",
  "3p-app": "acct_3p_apps",
  "contact-card": "acct_gf_contacts",
  gui: "",
  fusion: "acct_fusions",
  workflow: "acct_gf_workflows",
  "upload-designs": "acct_upload_designs",
} as const;

export const DB_NAME = "mydatabase";
export const FINETUNE_BUCKET_NAME = "gf-machine-learner";
export const APP_CONFIGURATION_SLUG = "test";
export const FUSION_EVENT_BUS_NAME_PREFIX = `${APP_NAME}-${STAGE}`;
